# -*- coding: utf-8 -*-
"""Pos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_bEi9hBBE5RsA-sKzlsAPfxBrhj58lO

# Greek lemmatizer and Pos-tagging
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Odycy"""

!pip install --quiet spacy-transformers==1.3.5

!pip install --quiet spacy==3.7.4

!pip install --quiet "numpy<2.0" --force-reinstall

!pip install --quiet https://huggingface.co/chcaa/grc_odycy_joint_trf/resolve/main/grc_odycy_joint_trf-0.7.0-py3-none-any.whl


import grc_odycy_joint_trf
nlp = grc_odycy_joint_trf.load()

def pos_tagger(text):
  doc = nlp(text)
  results = []

  for token in doc:
    results.append(token.pos_)

  return results

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/brill_dictionary_processed.csv')

for i, row in df.iterrows():
  pos = row['part_of_speech']

  if pd.isna(pos) or str(pos).strip() == '':
      tags = pos_tagger(row['lemma_raw'])
      df.at[i, 'part_of_speech'] = tags[0]
      print(i)

df.to_csv('/content/drive/MyDrive/odycy.csv', index=False)